version: '3'

services:
  web:
    restart: always
    build: .
    ports:
      - '8000:8000'
    volumes:
      - '.:/app'
    links:
      - db
    env_file:
      - '.env'

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - '.env'

  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'