version: '3'

services:
  web:
    restart: always
    build: .
    ports:
      - '8000:8000'
    volumes:
      - '.:/app'
    links:
      - db
    env_file:
      - '.env'

  db:
    image: mysql
    command: >
      --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'suricato_nparts'
    restart: always
    ports:
      - '3307:3306'
    networks:
      - db
    env_file:
      - '.env'

  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
    links:
      - db
    networks:
      - db

networks:
  db:
    driver: bridge
