version: '3'

services:
  web:
    restart: always
    build: .
    ports:
      - '8000:8000'
    volumes:
      - '.:/app'
    links:
      - db
    env_file:
      - 'docker.env'

  db:
    image: mysql
    command: >
      --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'suricato_nparts'
    restart: always
    volumes:
      - 'dbdata:/var/lib/mysql'
    ports:
      - '3307:3306'
    env_file:
      - 'docker.env'

  dbtest:
    image: mysql
    restart: always
    command: >
      --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 'teste'
      MYSQL_PASSWORD: 'teste'
      MYSQL_USER: 'root'
      MYSQL_DATABASE: 'suricato_testing'
    volumes:
      - 'dbtestdata:/var/lib/mysql'
    ports:
      - '3308:3306'

  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
    links:
      - db
      - dbtest

volumes:
  dbdata:
  dbtestdata: